"""added post date 

Revision ID: 22d8251eebe5
Revises: a101dc610672
Create Date: 2023-11-21 17:32:28.566562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d8251eebe5'
down_revision = 'a101dc610672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('publish_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('publish_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
