"""edit Password Hashing

Revision ID: 2cde4f0244f5
Revises: a8ac94718166
Create Date: 2023-11-19 10:46:13.218358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cde4f0244f5'
down_revision = 'a8ac94718166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passwordHashed', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('passwordHashed')

    # ### end Alembic commands ###
